version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tp-foyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  tp-foyer:
    depends_on:
      - mysqldb
    image: oumou2001/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - 8084:8084
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
      stdin_open: true
      tty: true
volumes:
  db :


